name: Update registry and index
on:
  push:
    branches:
      - '*'
    paths-ignore:
     - ['feature/*', 'develop']

jobs:
  udpate-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
