# TODO: write workflow for testing net-regsitry scripts
name: Test python scripts

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["*"]
jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Pylint
        run: |
          pip isntall pylint
      
      - name: Install python requirements
        run: |
          pip install -r scripts/requirements.txt

      - name: Run Pylint
        continue-on-error: false
        run: |
          find . -name '*.py' -exec pylint {} \;

      - name: Run unit-tests
        continue-on-error: false
        run: |
          chmod +x scripts/test_runner.sh
          ./scripts/test_runner.sh
